### ISSUE TITLE
Using weighted contrast on ordered factor with unbalanced samples

### ISSUE THREAD

**Issue by mdmanurung** [elbersb/weightedcontrasts#1]
Dear Dr. Elbers,

Is it okay to use weighted contrast on an ordered factor that was defined qualitatively? I am currently analysing health parameters that differs across the rural-urban gradient. The number of samples were not equal in rural, semi-urban, and urban groups. In contrast to your application for age, defining rural/urban is not clear-cut.. I would highly appreciate your input on this.

Thanks for taking the time.

Best regards,

**Comment by elbersb** [comment]
Hi! Do you have some sort of urban-rural scale that you're applying? Strictly speaking, the whole idea of polynomial contrasts probably only makes sense for truly continuous data

**Comment by mdmanurung** [comment]
Unfortunately, no. I decided to use ordinal regression instead. Thanks for your input!
